on: push

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: volta-cli/action@v3

      - name: Instalar dependencias
        run: npm install

      - name: Checar lint
        run: npm run lint

      - name: Compilar
        run: npm run build

      - name: Testes Unitários
        run: npm run test:unit
