on: push

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: volta-cli/action@v3
      - run: |
        npm install
        npm run lint
        npm run build
        npm run test:unit
