name: Deploy to Firebase Hosting on merge

'on':
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: volta-cli/action@v3

      - name: Instalar dependencias
        run: npm install

      - name: Checar lint
        run: npm run lint

      - name: Compilar
        run: npm run build

      - name: Deploy para produção
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_AGENDARIUM_DEV }}'
          channelId: live
          projectId: agendarium-dev
